### ISSUE TITLE
Battery support

### ISSUE THREAD

**Issue by MarvinSchenkel** [Madelena/esphome-weatherman-dashboard#5]
Amazing job, love this idea and want to get started myself. Instead of a dedicated cable, I would like to use a battery. Would that be as easy as connecting a powerbank to the ESP chip? Any idea what the battery life would be?

**Comment by Madelena** [comment]
Let me try to plug in a power meter and see how much it uses in a day.

You can use any USB battery packs, and if you're good at electronics, you can also have ESPHome measure the voltage of a battery to calculate its remaining battery percentage: https://ezcontents.org/esp8266-battery-level-meter

**Comment by Madelena** [comment]
![20220715_171603](https://user-images.githubusercontent.com/4341881/179420831-1977a81e-2d2a-4b55-8c99-36e398535276.jpg)

I plugged in my Klein Tools volt meter and found that it used 1900mAh after 26 hours, so that means it will drain a 10000mAh battery in 5 days. Battery usage can probably be lowered a lot if the screen doesn't need to refresh every minute.

**Comment by MarvinSchenkel** [comment]
Ouch, that’s a lot more than I had hoped. Thanks for taking the time to measure this. Realistically I’m too lazy to charge this every 5 days , so I’ll have to see if I can find a good spot for this first :)

**Comment by PolestarWx** [comment]
Do you have explored the use of ESP NOW protocol to use deep sleep and wake on wifi for ESP32 ?
https://github.com/iphong/lib-esp-rc

Someone developped integration of ESP NOW protocol for Hassio
https://github.com/iphong/esphome-espnow
